import { Blueprint, Material, Seriality } from '@/entities/blueprints/types';
import { NextResponse } from 'next/server';

export async function GET() {
    return NextResponse.json<Blueprint[]>([
        {
            id: 101,
            title: 'Проект Д-1',
            image_url: '/media/d1.webp',
            price: 10_000_000,
            material: Material.bricks,
            seriality: Seriality.serial,
            floors: 3,
            rooms: 6,
            bedrooms: 3,
            bathrooms: 2,
            area: 250,
        },
        {
            id: 102,
            title: 'Проект Д-2',
            image_url: '/media/d2.jpg',
            price: 15_000_000,
            material: Material.aeratedConcrete,
            seriality: Seriality.individual,
            floors: 2,
            rooms: 7,
            bedrooms: 3,
            bathrooms: 2,
            area: 300,
        },
        {
            id: 103,
            title: 'Проект Д-3',
            image_url: '/media/d3.jpg',
            price: 8_000_000,
            material: Material.aeratedConcrete,
            seriality: Seriality.serial,
            floors: 2,
            rooms: 5,
            bedrooms: 2,
            bathrooms: 1,
            area: 150,
        },
        {
            id: 201,
            title: 'Проект Б-1',
            image_url: '/media/b1.jpg',
            price: 5_000_000,
            material: Material.timber,
            seriality: Seriality.serial,
            floors: 1,
            rooms: 3,
            bedrooms: 0,
            bathrooms: 1,
            area: 100,
        },
        {
            id: 202,
            title: 'Проект Б-2',
            image_url: '/media/b2.jpg',
            price: 6_000_000,
            material: Material.timber,
            seriality: Seriality.serial,
            floors: 1,
            rooms: 3,
            bedrooms: 0,
            bathrooms: 1,
            area: 120,
        },
        {
            id: 301,
            title: 'Проект С-1',
            image_url: '/media/s1.jpg',
            price: 1_000_000,
            material: Material.timber,
            seriality: Seriality.serial,
            floors: 1,
            rooms: 1,
            bedrooms: 0,
            bathrooms: 0,
            area: 40,
        },
        {
            id: 302,
            title: 'Проект С-2',
            image_url: '/media/s2.jpg',
            price: 1_100_000,
            material: Material.aeratedConcrete,
            seriality: Seriality.serial,
            floors: 1,
            rooms: 1,
            bedrooms: 0,
            bathrooms: 0,
            area: 45,
        },
        {
            id: 401,
            title: 'Проект Г-1',
            image_url: '/media/g1.jpg',
            price: 1_500_000,
            material: Material.bricks,
            seriality: Seriality.serial,
            floors: 1,
            rooms: 1,
            bedrooms: 0,
            bathrooms: 0,
            area: 55,
        },
        {
            id: 402,
            title: 'Проект Г-2',
            image_url: '/media/g2.jpg',
            price: 500_000,
            material: Material.aeratedConcrete,
            seriality: Seriality.serial,
            floors: 1,
            rooms: 1,
            bedrooms: 0,
            bathrooms: 0,
            area: 20,
        },
    ]);
}
